version: "3.3"

services:
  web-app:
    image: "web-app"
    ports:
      - "8000:8000"
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
